version: '2'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      - MONGO_URL=mongodb://db:27017/launchandlearn
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
  db:
    image: mongo
    expose:
      - "27017"

